### ISSUE TITLE
ng5 compilation issues

### ISSUE THREAD

**Issue by tomatosource** [ngx-prism/core#2]
Am getting the following while trying to `ng-serve` with angular 5. 
```
ERROR in ./node_modules/@ngx-prism/core/dist/prism.component.ts
Module build failed: Error: [path...]/node_modules/@ngx-prism/core/dist/prism.component.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile ([path].../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then ([path..]/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/@ngx-prism/core/dist/index.js 2:0-51
 @ ./src/bits/app.module.ts
 @ ./src/bits/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/bits/main.ts
```

I believe this to be related to https://github.com/angular/angular-cli/issues/8284 namely 

> @rolaveric's case is slightly different. You have TS files in your node_modules. This really goes against how libraries should be packaged: libraries should never ship their source .ts files.

Any chance of getting a transpiled version of the lib we can use directly? 

[awesome lib btw!!!]

**Comment by sciborrudnicki** [comment]
This script should not copy all `ts` files only `html` files. It is mistake. Next version is coming today, with everything fixed and working with ng5 :)

**Comment by tomatosource** [comment]
Thanks for that, still a small issue though - looks like the `themes/*.css` are no longer being copied in?

**Comment by sciborrudnicki** [comment]
@tomatosource, i decied to not copy files to not double them. You can do it like below:

```css
@import '~prismjs/themes/prism-coy.css';
@import '~prismjs/themes/prism-dark.css';
@import '~prismjs/themes/prism-funky.css';
@import '~prismjs/themes/prism-okaidia.css';
@import '~prismjs/themes/prism-solarizedlight.css';
@import '~prismjs/themes/prism-tomorrow.css';
@import '~prismjs/themes/prism-twilight.css';
@import '~prismjs/themes/prism.css';
```
